### ISSUE TITLE
Sort most recent items first on serial records.

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#23]
For sorting of items on serial records, sort from most recent to oldest. On multi-volume monographs, sort from oldest to most recent.

**Comment by bbusenius** [comment]
As far as I know there isn't anything at all in the code that differentiates between serials and monographs and there's only 1 sort point for items in this case. In order to sort these differently we'll need to create a way of differentiating between monographs and serials. I'm not sure how to do that.

**Comment by dbietila** [comment]
You might be able to use the Book and Serial definition characteristics listed here:

https://loop.lib.uchicago.edu/documentation/ole-vufind/vufind/format-facet-definitions/

**Comment by dbietila** [comment]
This looks good on the examples I checked.
