### ISSUE TITLE
Help link for SCRC

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/vufind#97]
For items with a location with an SCRC building code, we should replace the service:
"Need help? - Ask a Librarian"
with a new service.

The label for the new service will be:
"Need help? - Ask SCRC or Request Scans"

This should open a new form, which functions like the form at:
http://forms2.lib.uchicago.edu/lib/request/help.php?bib=250908&barcode=16773038

This new form should submit request to the SCRC LibAnswer queue, rather than the Ask A Librarian queue. The email for the SCRC queue is:
askscrc@uchicago.libanswers.com (instead of askus@uchicago.libanswers.com)
I'm not sure whether Keith will need to be involved to provide handling for emails from this form.

**Comment by bbusenius** [comment]
Just to confirm regarding the `askscrc` SCRC LibAnswer queue. It looks like we already have a [CGIMail surrogate](https://www2.lib.uchicago.edu/keith/tmp/cgimail.html) of `askscrc`. You can see it on the[ SCRC class request form](https://www.lib.uchicago.edu/scrc/visiting/teaching/request-instruction/) as the value for the `rcpt` input. This is the surrogate I'll use and since it already exists, I don't think Keith should need to be involved.

**Comment by bbusenius** [comment]
This is [setup on dldc1](https://dldc1.lib.uchicago.edu/vufind/Record/9783727) as I think it needs to be. Currently the website form is submitting to my email. I can switch it over to the `askscrc` queue at any time.
